
uploadLocation: ./target/

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/testdb
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create

server:
  type: simple
  rootPath: '/service/*'
  applicationContextPath: /

logging:
  level: INFO
  loggers:
    com.gilmour.nea: DEBUG
    org.hibernate.SQL:
      level: DEBUG
